### ISSUE TITLE
Record Sessions into save-data/

### ISSUE THREAD

**Issue by Koloss0** [UMSATS/soti#35]
Create a `save-data/sessions/` directory under which sessions are saved. It should contain all messages, incoming and outgoing during the course of a session. Store sessions as YAML files.

Here is an example of what your files should look like:

```yaml
date: '10-15-2024'
time: '16:23'
session-length: '00:01:14'
port: 'COM3'
messages:
  - time: '16:23:51.267'
    sender: CDH
    recipient: PLD
    cmd: PLD_SET_ACTIVE_ENVS
    priority: 32
    ack: False
    body:
      bitmap: 0b0000000000000000
  # And so on...
```
